# Source of truth for which release assets become manifest entries.
# Copy this to the ROOT of your patches repo as `patches.toml`.

server_id            = "pinecraft"
client_version       = "3.3.5a-12340"
realmlist            = "logon.pinecraft.eu"
locale               = "enUS"
min_launcher_version = "0.1.0"

# Custom patches
[[file]]
asset    = "patch-enUS-4.MPQ"
path     = "Data/enUS/patch-enUS-4.MPQ"
required = true

[[file]]
asset    = "patch-Z.mpq"
path     = "Data/patch-Z.MPQ"
required = true

[[file]]
asset    = "patch-E.mpq"
path     = "Data/patch-E.MPQ"
required = true
